import type { Metadata } from "next";
import { PageIntro } from "../components/SiteShell";

export const metadata: Metadata = { title: "PapyrusAI" };

export default function PapyrusPage() {
  return <>
    <PageIntro eyebrow="PapyrusAI" title="PapyrusAI" description="A generative AI environment designed to support writing development and AI literacy. PapyrusAI is one of the central tools being developed and studied through the WRITE AI Center." />
<section className="section two-column-story"><div><p className="eyebrow">What is PapyrusAI?</p><h2>A structured environment for writing instruction.</h2></div><div className="prose"><p>PapyrusAI is a web-based platform that allows students to interact with a large language model through an environment designed specifically for writing instruction.</p><p>The platform was originally developed by a UCI research team with National Science Foundation funding and is now being further developed and evaluated through WRITE AI.</p></div></section>
    <section className="section institutional-section"><div className="section-heading"><p className="eyebrow">Flexible access</p><h2>Available through Google and Canvas.</h2><p>PapyrusAI supports Google sign-in and access through Canvas, making it easier for students and instructors to use the platform within their existing course environment.</p></div></section>
    <section className="section institutional-section"><div className="section-heading"><p className="eyebrow">Designed around learning</p><h2>Support students without completing the work for them.</h2></div><div className="five-card-grid">{[["Plan","Develop ideas, goals, audience awareness, and organization."],["Draft","Think through writing decisions and approaches."],["Revise","Evaluate and improve existing writing."],["Reflect","Consider writing choices and process."],["Build AI Literacy","Practice prompting, questioning, evaluating, and refining AI output."]].map(([title,copy])=><article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">How it works</p><h2>Structure keeps learning at the center.</h2></div><div className="approach-grid">{[["Guided Conversations","Students interact with AI through a conversational interface that begins with research-based embedded prompts."],["Instructor Control","Instructors determine which prompts are available and can modify them to match course objectives and student needs."],["Research-Based Scaffolding","Prompts encourage students to explain, reflect, and make decisions rather than simply receive completed writing."],["AI Literacy","Students practice evaluating AI responses, asking follow-up questions, and recognizing incomplete or incorrect output."]].map(([title,copy])=><article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="teacher-loop"><div><p className="eyebrow light">Teacher in the loop</p><h2>Instructor judgment remains central.</h2></div><p>Teachers can shape AI interactions according to their course context. WRITE AI is also studying how instructor-facing analytics might provide useful information about student needs and AI use.</p></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">The three core components</p><h2>A complete instructional environment.</h2></div><div className="three-grid">{[["Web Portal","A student-facing environment for interacting with AI without requiring direct access to the underlying model."],["Embedded Prompts","Research-based prompts that structure interactions and establish how the AI should and should not respond."],["Instructional Resources","Materials and professional development that support educators and students in using AI effectively."]].map(([title,copy],index)=><article className="feature-card" key={title}><span>0{index+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="section institutional-section"><div className="section-heading"><p className="eyebrow">What WRITE AI is developing next</p><h2>Continuing improvement with instructors and students.</h2></div><ul className="development-list"><li>Interface improvements</li><li>Expanded prompt libraries</li><li>Improved instructor dashboards</li><li>Additional learning analytics</li><li>Stronger pedagogical guardrails</li><li>Exploration of multi-agent AI systems</li></ul></section>
  </>;
}
