import { SiteLink as Link } from "./components/SiteLink";
import { partners } from "./data/site";

const work = [
  ["Research AI and Writing", "We study how generative AI is being used in postsecondary writing instruction and how it affects teaching, learning, and student outcomes."],
  ["Develop and Study PapyrusAI", "We are further developing and evaluating PapyrusAI, a guided generative AI environment designed to support writing development and AI literacy."],
  ["Build Research Capacity", "We provide training and opportunities for researchers, educators, and institutional leaders to strengthen their ability to evaluate generative AI in education."],
  ["Share Evidence and Resources", "We translate research into practical guidance, training, and resources that can support responsible AI use across postsecondary education."],
];

export default function Home() {
  return (
    <>
      <section className="hero institutional-hero">
        <div className="hero-copy"><p className="eyebrow">Improving writing education in the age of AI</p><h1>Improving Writing Education in the Age of AI</h1><p className="hero-deck">WRITE AI is a national research center studying how generative AI can be used effectively, responsibly, and equitably to improve writing instruction in postsecondary education.</p><p className="hero-deck secondary-deck">Through research, technology development, training, and national collaboration, the Center is building evidence to help students, educators, researchers, and institutions navigate writing in the age of AI.</p><div className="button-row"><Link className="button" href="/research">Explore Our Research →</Link></div></div>
        <div className="hero-visual" aria-label="Writing, educators, AI literacy, and research connected to College and Career Success"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="concept concept-writing"><span>Writing</span></div><div className="concept concept-ai"><span>AI<br />literacy</span></div><div className="concept concept-educators"><span>Educators</span></div><div className="concept concept-research"><span>Research</span></div><div className="concept concept-learning"><span>College and<br />Career Success</span></div></div>
      </section>
      <section className="section"><div className="section-heading"><p className="eyebrow">What we do</p><h2>Research, development, capacity, and evidence.</h2></div><div className="four-grid">{work.map(([title, copy], index)=><article className="function-card" key={title}><span className="card-index">0{index+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
      <section className="section two-column-story institutional-section"><div><p className="eyebrow">Why this work matters</p><h2>Writing remains essential.</h2></div><div className="prose"><p>Writing remains essential for success in college, work, and everyday life. Yet what it means to write well, and how we teach and assess writing, has changed dramatically in the era of AI.</p><p>Generative AI creates new opportunities for personalized writing support, but it also raises important questions about student learning, overreliance, privacy, bias, academic integrity, and responsible use.</p><p>WRITE AI studies how institutions can take advantage of AI’s potential without losing sight of the learning that writing is meant to develop.</p></div></section>
      <section className="papyrus-feature"><div className="papyrus-copy"><p className="eyebrow light">Featured work</p><h2>PapyrusAI</h2><p>PapyrusAI is a web-based generative AI platform designed to support writing and AI literacy through structured, research-based interactions.</p><p>The platform helps students engage with AI throughout the writing process while giving instructors greater control over how AI is used in their courses.</p><Link className="button button-light" href="/papyrus-ai">Learn About PapyrusAI →</Link></div><div className="guided-flow">{[["01","Plan"],["02","Draft"],["03","Revise"],["04","Reflect"]].map(([number,label])=><div className="flow-step" key={number}><span>{number}</span><strong>{label}</strong></div>)}</div></section>
      <section className="partners-section"><div><p className="eyebrow">A national collaboration</p><h2>Complementary expertise, shared purpose.</h2><p>WRITE AI brings together expertise in writing research, postsecondary education, generative AI, educational technology, research and evaluation, and institutional leadership.</p></div><div className="partner-grid">{partners.map((partner) => <Link className="partner-link" href={partner.href} key={partner.name}>{partner.name}</Link>)}</div></section>
      <section className="section"><div className="section-heading split-heading"><div><p className="eyebrow">Latest from WRITE AI</p><h2>Research, events, and resources.</h2></div><Link className="text-link" href="/news">View All News →</Link></div><div className="three-grid">
        <article className="resource-card"><div className="resource-meta"><span>Research update</span></div><h3>National AI writing landscape study</h3><p>WRITE AI is planning a public study of the tools, uses, requirements, and evidence shaping AI-supported writing instruction.</p><Link className="text-link" href="/research">Read research overview →</Link></article>
        <article className="resource-card"><div className="resource-meta"><span>Upcoming event</span></div><h3>AI in Higher Education</h3><p>A UCI professional-learning course beginning September 29, 2026, for higher-education instructors and instructional-support professionals.</p><Link className="text-link" href="/training-events">View event →</Link></article>
        <article className="resource-card"><div className="resource-meta"><span>Resource</span></div><h3>PapyrusAI Instructor Guide</h3><p>Practical guidance from the Digital Learning Lab for instructors using PapyrusAI.</p><Link className="text-link" href="https://docs.google.com/document/d/1o3He0CdgV7hJOX65gc3Gpf3_Fr3GYvSm4Q-i-Y5cNHQ/edit?usp=sharing">Open guide →</Link></article>
      </div></section>
    </>
  );
}
