import type { Metadata } from "next";
import { SiteLink as Link } from "../components/SiteLink";
import { PageIntro } from "../components/SiteShell";

export const metadata: Metadata = { title: "Research" };

export default function ResearchPage() {
  return <>
    <PageIntro eyebrow="Research" title="Research" description="WRITE AI studies how generative AI is being used in postsecondary writing instruction, how AI-supported approaches can affect learning, and how institutions can implement these technologies responsibly. The Center combines exploratory research, design-based research, randomized evaluation, qualitative research, cost analysis, and implementation research." />
    <section className="section research-detail" id="landscape"><div className="detail-number">01</div><div><p className="eyebrow">Research question 1</p><h2>What generative AI tools are colleges using?</h2><p className="section-deck">WRITE AI is conducting an ongoing national study of generative AI tools used in postsecondary writing instruction.</p><ul className="research-bullets"><li>Which tools are being used</li><li>Where and how they are being used</li><li>Instructional features</li><li>Costs and infrastructure requirements</li><li>Training needs</li><li>Approaches to safety, bias, and fairness</li><li>Available evidence of impact</li></ul><p>The findings will contribute to a publicly accessible, searchable resource for researchers and practitioners.</p></div></section>
    <section className="section research-detail alternate" id="papyrus"><div className="detail-number">02</div><div><p className="eyebrow">Research question 2</p><h2>How can generative AI best support writing instruction?</h2><p className="section-deck">WRITE AI is working with community-college instructors and students to further develop PapyrusAI and related instructional resources.</p><ul className="research-bullets"><li>User experience</li><li>Prompt design</li><li>Student AI interactions</li><li>Instructor controls</li><li>Professional development</li><li>Instructional resources</li><li>Integration into writing courses</li></ul><p>The goal is to understand how AI can provide personalized support while reinforcing, rather than replacing, the writing process.</p></div></section>
    <section className="section research-detail" id="impact"><div className="detail-number">03</div><div><p className="eyebrow">Research question 3</p><h2>What impact does AI-supported writing instruction have?</h2><p className="section-deck">WRITE AI plans a randomized controlled trial in first-year composition courses across six community colleges.</p><ul className="research-bullets"><li>Writing quality</li><li>AI literacy</li><li>Student writing self-efficacy</li><li>Instructor self-efficacy</li><li>Access to personalized writing instruction</li><li>Course retention and student persistence</li><li>Later performance in writing-intensive courses</li></ul></div></section>
    <section className="section institutional-section"><div className="section-heading"><p className="eyebrow">Responsible and ethical AI</p><h2>Safety and responsibility are part of the research.</h2></div><div className="approach-grid">{[["Privacy","How student and instructor data are protected."],["Bias and Fairness","Whether AI-generated feedback differs across student populations."],["Academic Integrity","How AI can support learning without replacing student work."],["Transparency","How students understand where and how AI is being used."],["Student Agency","How students learn to question, evaluate, and refine AI output."]].map(([title,copy])=><article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">Research timeline</p><h2>Five years from exploration to guidance.</h2></div><div className="timeline"><div><b>Years 1–2</b><span>Exploratory research + iterative development</span></div><div><b>Year 3</b><span>Randomized controlled trial</span></div><div><b>Year 4</b><span>Case studies + continued implementation</span></div><div><b>Year 5</b><span>Final analysis + implementation guidance + dissemination</span></div></div></section>
    <section className="section two-column-story"><div><p className="eyebrow">From research to practice</p><h2>Evidence institutions can use.</h2></div><div className="prose"><p>The Center will use findings from across its studies to develop an Implementation Support Guide for institutions interested in adopting and evaluating AI-supported writing tools.</p><Link className="button button-ghost" href="https://www.genaied.org/higher-ed-resources.html">Explore DLL writing + AI resources →</Link></div></section>
  </>;
}
