export type PersonLink = { label: string; href: string };
export type Person = {
  slug: string;
  name: string;
  role: string;
  institution: string;
  title?: string;
  image?: string;
  description?: string;
  links?: PersonLink[];
};
export type PeopleSection = { id: string; name: string; people: Person[] };

export const peopleSections: PeopleSection[] = [
  { id: "leadership", name: "Leadership", people: [
    { slug: "mark-warschauer", name: "Mark Warschauer", role: "Center Director and Principal Investigator", institution: "University of California, Irvine", title: "Distinguished Professor of Education and Director, Digital Learning Lab", image: "/people/mark-warschauer.webp", description: "Mark Warschauer is a Distinguished Professor of Education and Director of the Digital Learning Lab at UC Irvine, with affiliated appointments in Informatics, Language Science, and Psychology. He has written more than 300 publications on digital and AI-based learning and is among the world's most widely cited scholars in these areas. Supported by more than $30 million in federal funding, his research examines how conversational agents can support young children's learning, how AI can be integrated with computer science for K-12 students, and how the PapyrusAI platform can strengthen secondary and college students' writing and AI literacy. At UC Irvine's School of Education, Dr. Warschauer has served as Associate Dean and Interim Dean and helped launch major undergraduate, doctoral, master's, and certificate programs. He began his career as a Spanish bilingual mathematics and ESL teacher and has taught and conducted research internationally. He is a Fellow of the American Educational Research Association and a Member of the National Academy of Education.", links: [{ label: "Personal website", href: "https://markwarschauer.com/" }] },
    { slug: "di-xu", name: "Di Xu", role: "Co-Principal Investigator", institution: "University of California, Irvine", title: "Professor", image: "/people/di-xu.webp", description: "Di Xu is a professor at the University of California, Irvine and a Co-Principal Investigator for the WRITE AI Center." },
    { slug: "tamara-tate", name: "Tamara Tate, PhD", role: "Co-Principal Investigator", institution: "University of California, Irvine", title: "Project Scientist and Associate Director, Digital Learning Lab", image: "/people/tamara-tate.webp", description: "Tamara Tate, PhD, is a Project Scientist at UC Irvine and Associate Director of the Digital Learning Lab, where she leads work on generative AI, writing, and digital learning. Her research focuses on how AI and other digital tools can support writing instruction, digital literacy, and student learning across secondary and postsecondary education. As PI of multiple grants on AI-based writing, including NSF-funded work, she has led efforts to develop generative AI writing tools, curricula, and faculty resources that integrate AI into teaching and learning without offloading essential skill development. A frequent speaker on AI in education, Dr. Tate teaches AI in Education courses for master’s students and higher education instructors, helping educators critically and responsibly integrate AI into teaching and learning. She is also part of intersegmental efforts across California’s public higher education systems to advance responsible AI use in academic writing and digital literacy. Dr. Tate brings an interdisciplinary background in education, English, and law, with a PhD and BA from UC Irvine and a JD from UC Berkeley." },
    { slug: "alexander-mayer", name: "Alex Mayer", role: "Co-Principal Investigator", institution: "MDRC", title: "Director, Postsecondary Education", image: "/people/alexander-mayer.webp", description: "Alex Mayer is Director of Postsecondary Education at MDRC and a Co-Principal Investigator for the WRITE AI Center.", links: [{ label: "LinkedIn", href: "https://www.linkedin.com/in/alex-mayer-1a73693" }] },
    { slug: "richard-hendra", name: "Richard Hendra", role: "Co-Principal Investigator", institution: "MDRC", title: "Senior Fellow and Director of Data Strategy and Innovation", image: "/people/richard-hendra.webp", description: "Richard Hendra is a Senior Fellow and Director of Data Strategy and Innovation at MDRC and a Co-Principal Investigator for the WRITE AI Center.", links: [{ label: "LinkedIn", href: "https://www.linkedin.com/in/richard-hendra-67b60a4/" }] },
    { slug: "jory-hadsell", name: "Jory Hadsell", role: "Co-Principal Investigator", institution: "California Community Colleges Chancellor’s Office", title: "Executive in Residence, Strategic Technology Initiatives", image: "/people/jory-hadsell.webp", description: "Jory Hadsell serves as Vice Chancellor of Technology and Innovation for the Foothill-De Anza Community College District as well as Executive in Residence for Strategic Technology Initiatives with the California Community Colleges Chancellor’s Office, where he provides statewide leadership for technology strategy, enterprise systems, infrastructure, cybersecurity, data governance, digital transformation, and innovation supporting the California Community Colleges. Hadsell serves as an executive leader for the Digital Center for Innovation, Transformation and Equity, a statewide hub focused on accelerating technology-enabled innovation, collaboration, and equitable student success. His portfolio includes leadership and strategic oversight of initiatives involving artificial intelligence, data modernization, cloud technologies, digital learning, and emerging technology. This includes the Online Network of Educators (@ONE), a statewide program focused on strengthening online teaching and learning through professional development, resources, and support for California Community Colleges faculty. Throughout his work, Hadsell brings together institutional leaders, technology professionals, faculty, state partners, and industry organizations to translate emerging technologies into scalable solutions for higher education. His leadership emphasizes responsible innovation, cross-institutional collaboration, sustainable technology strategy, and alignment with the California Community Colleges’ broader goals for access, equity, and student success." },
    { slug: "justin-schultz", name: "Justin Schultz", role: "Co-Principal Investigator", institution: "Foothill-De Anza Community College District", title: "Director of Strategic Planning and Operations", image: "/people/justin-schultz.webp", description: "Justin Schultz serves as Director of Strategic Planning and Operations for the Foothill-De Anza Community College District and provides strategic, administrative, operational, fiscal, and project leadership for the Digital Center for Innovation, Transformation and Equity. His work focuses on translating strategic priorities and emerging opportunities into scalable initiatives while developing the administrative and operational structures necessary to support their successful implementation. Schultz supports a portfolio of statewide California Community Colleges technology and innovation initiatives spanning artificial intelligence, digital learning, data modernization, interoperability, and student-centered technology. His responsibilities include portfolio and project management, grant and fiscal administration, budgeting, procurement and contracting, organizational planning, stakeholder engagement, and coordination across institutional, state, and industry partners. His current work includes leadership supporting the Common Cloud Data Platform, California Career Passport, eTranscript California, and the Digital Center’s expanding innovation portfolio, including the Online Network of Educators (@ONE). Schultz specializes in coordinating complex, multi-partner initiatives involving colleges, state agencies, technology partners, vendors, and cross-functional teams. His work emphasizes effective administration, responsible stewardship of public and grant resources, collaborative implementation, and sustainable operational models that enable innovative projects to progress from strategy and experimentation toward scalable systemwide adoption." },
    { slug: "hironao-okahana", name: "Hironao Okahana", role: "Co-Principal Investigator", institution: "American Council on Education" },
    { slug: "sheri-prupis", name: "Sheri L. Prupis, PhD", role: "Co-Principal Investigator", institution: "Virginia Community College System", title: "Director, Teaching & Learning with Technology / Project Director, Digital Accessibility Compliance Initiative", image: "/people/sheri-prupis.webp", description: "Dr. Sheri Prupis serves as Director of Teaching and Learning with Technology for the Virginia Community College System, where she also leads the system's Digital Accessibility Compliance Initiative. In her role, she works at the intersection of andragogy, policy, and technology, helping shape a system-wide vision for teaching and learning across Virginia's 23 community colleges. Sheri contributes to national conversations through EDUCAUSE, WCET, and the Instructional Technology Council, while teaching sociology and using the tools and approaches she supports system-wide. Her research explores teaching and learning with technology, faculty-student relationships in asynchronous courses in an AI-world, LMS design, and qualitative research methods. She holds a PhD in Educational Leadership from Old Dominion University. She has served as PI or co-PI on several federally and state-funded initiatives, including grants supporting digital course redesign and statewide media infrastructure.", links: [{ label: "LinkedIn", href: "https://www.linkedin.com/in/sheriprupis/" }] },
  ] },
  { id: "research-development", name: "Research and Development Team", people: [
    { slug: "michael-hebert", name: "Michael Hebert", role: "Writing Evaluation", institution: "UC Irvine School of Education", title: "Associate Dean of Teacher Education", image: "/people/michael-hebert.webp", description: "Dr. Michael Hebert is a Professor, Associate Dean of Teacher Education, and Director of the Writing Project at UC Irvine. His primary interests include writing instruction and assessment, and the impacts of writing on reading. Dr. Hebert has more than 65 publications, including two influential Carnegie Corporation reports: Writing to Read and Informing Writing. He is also the co-editor of The Hitchhiker’s Guide to Writing Research: A Festschrift for Steve Graham, and Best Practices in Writing Instruction, third edition. He was previously an elementary classroom teacher and reading specialist in schools in New Hampshire, Massachusetts, California, and the Navajo Nation.", links: [{ label: "Faculty profile", href: "https://faculty.uci.edu/profile/?facultyId=7216" }] },
    { slug: "beth-harnick-shapiro", name: "Beth Harnick-Shapiro", role: "Disciplinary Writing", institution: "UC Irvine and Cal State Fullerton", title: "Lecturer", image: "/people/beth-harnick-shapiro.webp", description: "Beth Harnick-Shapiro has taught and promoted faculty and student engagement in all three tiers of California public higher education. Her current teaching focuses on professional communication, ethics, and AI. At UC Irvine’s Samueli School of Engineering, she coordinates and teaches upper-division professional writing. As a member of UCI’s Digital Learning Lab, she conducts research on human-centered AI in Engineering education. At Cal State Fullerton, she teaches Computer Science courses and coordinates the Women in Computer Science and Engineering program. She is a principal investigator on a California Learning Lab Grand AI Challenge intersegmental initiative to explore how to enhance academic writing and digital literacy with an AI Coach.", links: [{ label: "Personal website", href: "https://sites.google.com/uci.edu/bhs" }, { label: "LinkedIn", href: "https://www.linkedin.com/in/beth-harnick-shapiro/" }] },
    { slug: "penelope-collins", name: "Penelope Collins", role: "Developmental Writing", institution: "University of California, Irvine", title: "Professor", description: "Penelope Collins is a professor at the University of California, Irvine who contributes expertise in developmental writing to the WRITE AI Center.", links: [{ label: "Personal website", href: "https://sites.google.com/uci.edu/penelopecollins/home" }] },
    { slug: "kristi-werry", name: "Kristi Werry", role: "Software Engineering", institution: "University of California, Irvine" },
  ] },
  { id: "writing-advisors", name: "Writing Advisors", people: [
    { slug: "charles-macarthur", name: "Charles A. MacArthur", role: "Writing Advisor", institution: "University of Delaware", title: "Professor Emeritus", description: "Charles A. MacArthur, Ph.D., is Professor Emeritus in the School of Education at the University of Delaware. Major research interests include writing development and instruction, development of self-regulated strategies, and motivation with a focus on students who need extra support to be successful, including students with learning disabilities, college basic writers, and adult learners. He has directed ten federally funded research projects on writing instruction, including two projects focused on the development and evaluation of the Supporting Strategic Writers (SSW) approach. He has published three books on strategy instruction including one on the college curriculum, Writing Instruction for Success in College and the Workplace. Also, he has co-edited several books, including the Handbook of Writing Research, Best Practices in Writing Instruction, and Adult Education Literacy Instruction: A Review of the Research. Currently, he is consultant on an adult literacy project that is adapting the SSW approach for adult learners. In addition, he has also conducted research on the use of technology to support writing instruction. In 2020, he was named an AERA Fellow. In 2022, he received the Special Education Research Award from the Council for Exceptional Education (CEC), and a Leadership Award from the Division of Learning Disabilities." },
    { slug: "steve-graham", name: "Steve Graham", role: "Writing Advisor", institution: "Arizona State University" },
    { slug: "anna-mills", name: "Anna Mills", role: "Writing Advisor", institution: "College of Marin", title: "English Instructor, Textbook Author, and Faculty Developer", description: "Anna Mills is a leading voice on AI in higher education across platforms including LinkedIn, Substack, and BlueSky. She has taught writing in California community colleges for 20 years and is author of the OER textbooks AI and College Writing: An Orientation and How Arguments Work: A Guide to Writing and Analyzing Texts in College. Her writing appears in The Chronicle of Higher Education, Inside Higher Ed, Computers and Composition, and AIPedagogy.org. She serves on the Modern Language Association Task Force on AI in Research and Teaching. As a volunteer advisor, she has helped shape MyEssayFeedback.ai, and she serves as co-Principal Investigator for the Peer & AI Review + Reflection (PAIRR) project funded by the California Education Learning Lab.", links: [{ label: "Personal website", href: "https://annarmills.com/" }, { label: "LinkedIn", href: "https://www.linkedin.com/in/anna-mills-oer/" }] },
  ] },
  { id: "ai-learning-advisors", name: "AI and Learning Advisors", people: [
    { slug: "ryan-baker", name: "Ryan Baker", role: "AI and Learning Advisor", institution: "Adelaide University", title: "Professor", image: "/people/ryan-baker.webp", description: "Ryan Baker is Professor of Artificial Intelligence and Education at Adelaide University. Baker has developed models that can automatically detect student engagement in over a dozen online learning environments and led the development of an observational protocol and app for field observation of student engagement that has been used by over 150 researchers in 7 countries. Predictive analytics models he helped develop have been used to benefit over two million students, over a hundred thousand people have taken MOOCs he ran, and he has coordinated longitudinal studies that spanned over a decade. Baker was the founding president of the International Educational Data Mining Society, is Associate Editor of the Journal of Educational Data Mining, was the first technical director of the Pittsburgh Science of Learning Centre DataShop, currently serves as Co-Director of the JeepyTA learning platform, and founded two master’s degree programs in Learning Analytics. Baker has co-authored published papers with over 600 colleagues and has been cited over 40,000 times.", links: [{ label: "Personal website", href: "https://learninganalytics.upenn.edu/ryanbaker" }, { label: "LinkedIn", href: "https://www.linkedin.com/in/ryan-baker-36567482/" }] },
    { slug: "danielle-mcnamara", name: "Danielle McNamara", role: "AI and Learning Advisor", institution: "Arizona State University" },
  ] },
  { id: "ethics-advisors", name: "Ethics Advisors", people: [
    { slug: "renzhe-yu", name: "Renzhe Yu", role: "Ethics Advisor", institution: "Teachers College, Columbia University", title: "Assistant Professor", image: "/people/renzhe-yu.webp", description: "Renzhe Yu is an Assistant Professor of Learning Analytics at Teachers College, Columbia University, where he directs the AEQUITAS Lab and is affiliated with the Data Science Institute. With interdisciplinary training across education, public policy, computer science, and economics, his research centers on responsible AI in education and society. Specifically, he develops and applies evaluation frameworks for model fairness and generalizability, human-AI interaction, and digital divides in the wild. His work has led to over 40 publications in high-impact journals and conference proceedings such as Scientific Data and EMNLP, and has received multiple best paper awards and nominations. He has also been recognized by international research organizations such as AERA and the Alan Turing Institute through their awards and fellowship programs.", links: [{ label: "Personal website", href: "https://renzheyu.com" }] },
    { slug: "fred-oswald", name: "Fred Oswald", role: "Ethics Advisor", institution: "University of California, Irvine", title: "Professor", image: "/people/fred-oswald.jpg", description: "Fred Oswald, PhD, is a professor in the School of Education at the University of California, Irvine. As an industrial-organizational (I-O) psychologist, he and his graduate students have published extensively on the effects of AI on students' educational and career pathways, as well as the substance and psychometrics of employment, personality, and educational testing. Currently, he is Editor-in-Chief of Psychological Methods and has also served as Associate Editor at eight other journals. His prior leadership positions include serving as chair of the Board on Human-Systems Integration at the National Academy of Sciences (2020-2025), advisor to the White House as a member of the National Artificial Intelligence Advisory Committee (2022-2025), and President of the Society for Industrial and Organizational Psychology (2017-2018). For the American Psychological Association, he has served as Chair of the Board of Scientific Affairs, Chair of the Open Science and Methodology Committee, and Chair of the Committee on Psychological Tests and Assessment. He is a Fellow of SIOP, APA, and the Association for Psychological Science. Dr. Oswald received his PhD in industrial-organizational psychology from the University of Minnesota in 1999.", links: [{ label: "Personal website", href: "https://faculty.sites.uci.edu/foswald/" }, { label: "LinkedIn", href: "https://www.linkedin.com/in/fred-oswald/" }] },
  ] },
];

export const partnerOrganizations = [
  { name: "UC Irvine Digital Learning Lab", href: "/organizations/uc-irvine-digital-learning-lab" },
  { name: "MDRC", href: "/organizations/mdrc" },
  { name: "American Council on Education", href: "/organizations/american-council-on-education" },
  { name: "California Community Colleges’ Digital Center for Innovation, Transformation and Equity", href: "/organizations/california-community-colleges-foothill-de-anza" },
  { name: "Virginia Community College System", href: "/organizations/virginia-community-college-system" },
  { name: "Houston City College", href: "/organizations/houston-community-college" },
];

export function getPerson(slug: string) {
  for (const section of peopleSections) {
    const person = section.people.find((candidate) => candidate.slug === slug);
    if (person) return { ...person, section };
  }
  return undefined;
}
